### ISSUE TITLE
Module path should be "github.com/Zach-Johnson/bhugo", not "bhugo"

### ISSUE THREAD

**Issue by KateGo520** [Zach-Johnson/bhugo#11]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, run `go get github.com/Zach-Johnson/bhugo`:

```
go: downloading github.com/Zach-Johnson/bhugo v0.0.0-20190522182227-e6bde14eaa98
go: github.com/Zach-Johnson/bhugo upgrade => v0.0.0-20190522182227-e6bde14eaa98
go get: github.com/Zach-Johnson/bhugo@v0.0.0-20190522182227-e6bde14eaa98: parsing go.mod:
        module declares its path as: bhugo
                but was required as: github.com/Zach-Johnson/bhugo 
```

###  Fix the module path:
1) Rename the module path to "github.com/Zach-Johnson/bhugo": https://github.com/Zach-Johnson/bhugo/blob/master/go.mod#L1:
```
module github.com/Zach-Johnson/bhugo
go 1.12
require (
	…
) 
```
2) Warning the users not to use the module, get "github.com/Zach-Johnson/bhugo" in GOPATH mode.

**Comment by KateGo520** [comment]
@Zach-Johnson @rv-ssheffield   Could you help me review this issue? Thx :p

**Comment by Zach-Johnson** [comment]
@KateGo520 thanks for pointing this out, should be fixed now on latest commit of master.

**Comment by KateGo520** [comment]
@Zach-Johnson  Thanks for your efforts and feedback.
